name: datomworld_cljd
description: ClojureDart experiment for Datomworld
publish_to: 'none'
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.29.0

flutter:
  assets:
    - assets/shaders/simple_mesh.shaderbundle
    - assets/images/earth_land_ocean_ice_2048.jpg
    - assets/images/moon_texture_1024.jpg
    - assets/images/earth_land_ocean_ice_1024.jpg
    - assets/images/moon_texture_512.jpg
