(ns yang.python.antlr.parser
  "The Python parser interpreter (JVM host): the grammars-v4 Python3 grammar
   profile plus the stage that reads sealed source units from one stream and
   writes CST packets to another. The generated recognizers come from
   `clj -M:antlr-gen` (antlr/python3/manifest.edn); this is the only
   namespace that names them."
  (:require
    [yang.antlr.cst :as cst]
    [yang.stage :as stage])
  (:import
    (yang.python.antlr.gen
      Python3Lexer
      Python3Parser)))


(def grammar-id
  "grammars-v4 python/python3 at its pinned revision, generated by ANTLR 4.13.2."
  "grammars-v4/python/python3@8af0d4c26c796ea27c15c3d85418f2d0f77c3adb antlr-4.13.2")


(def profile
  {:grammar-id grammar-id,
   :make-lexer (fn [cs] (Python3Lexer. cs)),
   :make-parser (fn [ts] (Python3Parser. ts)),
   :start (fn [^Python3Parser p] (.file_input p))})


(defn make-worker
  []
  (cst/make-worker profile))


(defn parse-source
  "Parse one complete source string as unit `unit`: the packet a sealed unit
   with this text produces."
  ([source] (parse-source (make-worker) [:unit 0] source))
  ([worker unit source] (cst/parse-unit worker unit source)))


(defn open-stage
  "A parser stage reading source events from `source-stream` and writing
   CST packets to `cst-stream`, with its own worker."
  [source-stream cst-stream]
  (assoc (stage/open source-stream {:cst cst-stream} {})
         ::transform (cst/parse-transform (make-worker))))


(defn step-stage
  [s]
  (stage/step s (::transform s)))
