(ns dao.db
  "DaoDB: immutable database as a value. Datomic-compatible API.")


(defrecord Datom
  [e a v t m]
  #?@(:cljs
      [IIndexed
       (-nth [this n]
             (case n
               0 e
               1 a
               2 v
               3 t
               4 m
               (throw (js/Error. (str "Index out of bounds: " n)))))
       (-nth [this n not-found]
             (case n
               0 e
               1 a
               2 v
               3 t
               4 m
               not-found))]))


(defn ->datom
  [e a v t m]
  (->Datom e a v t m))


(defn- type-rank
  "Total ordering for heterogeneous datom values.
   nil < boolean < integer < float < string < keyword < symbol < other."
  [x]
  (cond
    (nil? x)     0
    (boolean? x) 1
    (integer? x) 2
    #?(:clj  (float? x)
       :cljs  (and (number? x) (not (integer? x)))
       :cljd  (dart/is? x double)) 3
    (string? x)  4
    (keyword? x) 5
    (symbol? x)  6
    :else         7))


(defn compare-vals
  "Compare two datom values across heterogeneous types using type-rank."
  [a b]
  (let [ra (type-rank a) rb (type-rank b)]
    (if (= ra rb) (compare a b) (compare ra rb))))


(def bootstrap-datoms
  "Reserved DaoDB system facts present in every empty database."
  [(->datom 1  :db/ident :db/derived          0 0)
   (->datom 2  :db/ident :db/ident            0 0)
   (->datom 3  :db/ident :db/valueType        0 0)
   (->datom 4  :db/ident :db/cardinality      0 0)
   (->datom 5  :db/ident :db/unique           0 0)
   (->datom 6  :db/ident :db/index            0 0)
   (->datom 7  :db/ident :db.cardinality/one  0 0)
   (->datom 8  :db/ident :db.cardinality/many 0 0)
   (->datom 9  :db/ident :db.type/ref         0 0)
   (->datom 10 :db/ident :db.type/string      0 0)
   (->datom 11 :db/ident :db.type/long        0 0)
   (->datom 12 :db/ident :db.type/boolean     0 0)
   (->datom 13 :db/ident :db.type/keyword     0 0)])


;; =============================================================================
;; Four-Component Architecture Boundaries
;; =============================================================================

(defprotocol IDaoStorage
  "Append-only log of datom segments, keyed by transaction range."

  (write-segment!
    [this segment]
    "Append a [t added retracted] log entry to storage. Returns updated db.")

  (read-segments
    [this t-min t-max]
    "Return a seq of [t added retracted] entries for t-min <= t <= t-max.")

  (latest-t
    [this]
    "Return the highest committed transaction ID."))


(defprotocol IDaoTransactor
  "Single writer. Serializes all transactions to preserve monotonic t."

  (transact!
    [this tx-data]
    "Apply tx-data. Returns {:db-after db :tempids {...} :tx-data [...]}.")

  (with
    [this tx-data]
    "Apply tx-data to db value without modifying state. Datomic d/with equivalent.
     Returns {:db-after ... :db-before ... :tx-data ... :tempids ...}."))


(defprotocol IDaoQueryEngine
  "Query execution engine. Runs Datalog queries and provides index access."

  (run-q
    [this query inputs]
    "Run a Datalog query. inputs is a seq of extra bindings beyond $.")

  (index-datoms
    [this index components]
    "Return datoms for index with optional leading-component filter seq."))


(defprotocol IDaoDB
  "Database as a value. Immutable snapshots and views of the database state."

  (entity
    [this eid]
    "Return entity map for eid with :db/id. Card-many attrs are sets.
     Returns nil if entity has no datoms.")

  (pull
    [this pattern eid]
    "Pull structured data using pattern for entity eid.
     Pattern: [*], [:attr1 :attr2], [{:ref-attr [:sub]}], or combinations.")

  (pull-many
    [this pattern eids]
    "Pull structured data for multiple eids. Returns vector of maps.")

  (basis-t
    [this]
    "Return the basis-t (last committed transaction ID).")

  (as-of
    [this t]
    "Return db snapshot containing only datoms with t <= tx.")

  (since
    [this t]
    "Return db snapshot containing only datoms with t > tx.")

  (entity-attrs
    [this eid]
    "Return map of {attr val} for entity. Card-many attrs are vectors.")

  (find-eids-by-av
    [this a v]
    "Return set of entity IDs where attribute = val."))


;; =============================================================================
;; Datomic-compatible top-level API
;;
;; Protocol methods entity, pull, pull-many, with, transact, basis-t, as-of,
;; since, entity-attrs, find-eids-by-av are already top-level vars generated by
;; defprotocol. q and datoms keep Datomic-compatible argument order and arity.
;; =============================================================================

(defn q
  "Datomic-compatible query: (q query & inputs) where $ binds to first input.
   Example: (q '[:find ?e :where [?e :name \"Alice\"]] db)"
  [query & inputs]
  (run-q (first inputs) query (rest inputs)))


(defn datoms
  "Datomic-compatible datoms: (datoms db index & components).
   Examples:
     (datoms db :eavt)           ; all datoms
     (datoms db :eavt eid)       ; all datoms for entity
     (datoms db :eavt eid attr)  ; all datoms for entity + attr
     (datoms db :avet attr val)  ; find entities by attr+val"
  ([db index] (index-datoms db index nil))
  ([db index & components] (index-datoms db index components)))


(defn transact
  "Transact tx-data. Returns {:db-after <new-db> :db-before <old-db> :tx-data [...] :tempids {...}}.
   Also includes :db as a backward-compat alias for :db-after."
  [db tx-data]
  (transact! db tx-data))
