(ns dao.db
  "DaoDB: immutable database as a value. Datomic-compatible API.")


(defprotocol IDaoDb

  (run-query
    [db query inputs]
    "Run a Datalog query. inputs is a seq of extra bindings beyond $.")

  (transact
    [db tx-data]
    "Transact tx-data. Returns {:db-after <new-db> :db-before <old-db> :tx-data [...] :tempids {...}}.
     Also includes :db as a backward-compat alias for :db-after.")

  (with
    [db tx-data]
    "Apply tx-data to db value. Datomic d/with equivalent.
     Returns {:db-after ... :db-before ... :tx-data ... :tempids ...}.")

  (index-datoms
    [db index]
    [db index components]
    "Return datoms for index (:eavt/:aevt/:avet/:vaet).
     components is an optional seq of leading key values to filter by.")

  (entity
    [db eid]
    "Return entity map for eid with :db/id. Card-many attrs are sets.
     Returns nil if entity has no datoms.")

  (pull
    [db pattern eid]
    "Pull structured data using pattern for entity eid.
     Pattern: [*], [:attr1 :attr2], [{:ref-attr [:sub]}], or combinations.")

  (pull-many
    [db pattern eids]
    "Pull structured data for multiple eids. Returns vector of maps.")

  (basis-t
    [db]
    "Return the basis-t (last committed transaction ID).")

  (as-of
    [db t]
    "Return db snapshot containing only datoms with t <= tx.")

  (since
    [db t]
    "Return db snapshot containing only datoms with t > tx.")

  (entity-attrs
    [db eid]
    "Return map of {attr val} for entity. Card-many attrs are vectors.")

  (find-eids-by-av
    [db attr val]
    "Return set of entity IDs where attribute = val."))


;; =============================================================================
;; Datomic-compatible top-level API
;;
;; Protocol methods entity, pull, pull-many, with, transact, basis-t, as-of,
;; since, entity-attrs, find-eids-by-av are already top-level vars generated by
;; defprotocol. Only q and datoms need wrappers due to different argument order.
;; =============================================================================

(defn q
  "Datomic-compatible query: (q query & inputs) where $ binds to first input.
   Example: (q '[:find ?e :where [?e :name \"Alice\"]] db)"
  [query & inputs]
  (run-query (first inputs) query (rest inputs)))


(defn datoms
  "Datomic-compatible datoms: (datoms db index & components).
   Examples:
     (datoms db :eavt)           ; all datoms
     (datoms db :eavt eid)       ; all datoms for entity
     (datoms db :eavt eid attr)  ; all datoms for entity + attr
     (datoms db :avet attr val)  ; find entities by attr+val"
  ([db index] (index-datoms db index))
  ([db index & components] (index-datoms db index components)))
