;; JVM-only writer for the dao.gui.event conformance fixture corpus.
;; Regenerates the committed .edn files under test/dao/gui/event/fixtures/
;; and the embedded corpus namespace from the scenario definitions in
;; dao.gui.event.fixtures-gen. Run from the repository root with the test
;; classpath:
;;
;;   CP=$(clj -A:test -Spath) && \
;;     java -cp "$CP" clojure.main -m dao.gui.event.fixtures-write
(ns dao.gui.event.fixtures-write
  (:require [clojure.pprint :as pprint]
            [dao.gui.event.fixtures-gen :as gen]))


(defn write-corpus!
  ([]
   (write-corpus! "test/dao/gui/event/fixtures"
                  "test/dao/gui/event/fixtures_corpus.cljc"))
  ([edn-dir corpus-path]
   (let [corpus (gen/corpus)]
     (doseq [[id fixture] corpus]
       (let [file (java.io.File. edn-dir
                                 (str (namespace id) "_" (name id) ".edn"))]
         (.mkdirs (.getParentFile file))
         (with-open [w (java.io.OutputStreamWriter. (java.io.FileOutputStream.
                                                      file)
                                                    "UTF-8")]
           (pprint/pprint fixture w))))
     (let [corpus-file (java.io.File. corpus-path)]
       (.mkdirs (.getParentFile corpus-file))
       (with-open [w (java.io.OutputStreamWriter. (java.io.FileOutputStream.
                                                    corpus-file)
                                                  "UTF-8")]
         (binding [*out* w]
           (println
             ";; GENERATED by dao.gui.event.fixtures-write: the embedded")
           (println ";; view of the committed EDN corpus. Regenerate with the")
           (println ";; generator; the .edn files are the conformance")
           (println ";; artifacts. Do not edit by hand.")
           (println "(ns dao.gui.event.fixtures-corpus)")
           (println)
           (println "(def corpus")
           (pprint/pprint corpus w)
           (println ")"))))
     (count corpus))))


(defn -main
  [& _args]
  (println "wrote" (write-corpus!) "fixtures"))
