(ns yin.vm.ucf.checkpoint-fixtures
  "The shared canonical fixtures of M-next C slice C4, regenerated by
   D9 through the real version-1 lift (UCF 7.2.1, 7.4.3, 7.7.8),
   pinned by their segment addresses, loaded on the JVM, Node and Dart.

   The five accepted bases are bodies the lift itself emitted: a machine
   the engine parked, entered, prepared under a header and encoded
   (`yin.vm.ucf.lift-support`), then decoded from its own canonical
   bytes.  Nothing about a base is hand-built but the one thing no code
   assigns yet: the operation ids (`lift-support/with-op-id`), which D11
   replaces.  Every other fixture is a mutation of a named base, found
   by predicate, never by index, so a change in what a real lift emits
   moves the mutation with it.  A mutation names the path its refusal
   reports (`expected`) and the place it changed (`place`), and the test
   proves the body differs there.

   The pins live in test/resources/yin/vm/ucf/checkpoint-v1.txt, one
   block per fixture separated by a blank line: the name and the
   segment address of its bytes.  Three anchors (`anchors`) also keep
   their full bytes as lowercase hex in lines of 64 digits, so the
   inspector reads bytes this build did not produce.  Every other
   fixture's bytes are built from its body and checked against its
   pinned address; `non-canonical` patches the `successor` anchor's
   bytes.  Regenerate the file from a JVM REPL with the string `render`
   returns, saved to `path`; the test proves on every host that the file
   equals `render`.

   The bases' streams carry no random identity (`lift-support`'s
   `:make-stream`), so the bytes are the same on every run and host.
   `counter-at-bound` stays a mutation: a conforming lift refuses a
   counter of 2^52-1, so none can emit it, and the inspector still
   accepts it."
  (:require [clojure.string :as str]
            [dao.jing :as jing]
            [dao.jing.cbor :as cbor]
            [dao.jing.cbor-fixtures :as fx]
            [yin.vm.ucf.lift-support :as s]))


(def path
  "The fixture file, relative to the repository root."
  "test/resources/yin/vm/ucf/checkpoint-v1.txt")


(def max-exact 4503599627370495)


(def occurrence s/occurrence)
(def predecessor s/predecessor)
(def origin s/origin)
(def arbitration s/arbitration)
(def op-id s/op-id)


;; =============================================================================
;; Accepted bases: real lifts, decoded from their own bytes
;; =============================================================================

(defn- lifted
  "The body of the real lift of `machine` under `header`, as decoded
   from its canonical bytes."
  [machine header]
  (let [r (s/lift machine header)]
    (when-not (= :ok (:status r))
      (throw (ex-info "A fixture base failed to lift" (dissoc r :record))))
    (cbor/decode (:bytes r))))


(def ^:private child-path [:yin.k/installs 'host.mod :yin.k/child])


(def ^:private base-bodies
  {"first-park" (lifted (s/parked-reader) (s/header 0 nil #{}))

   "successor"
   (lifted (s/with-op-id (s/parked-writer) :put (op-id 0))
           (s/header 3 origin #{"s0"}))

   ;; a root waiting on an install whose child is blocked on a write
   ;; drawing id 4 from the root's sequence
   "installs"
   (lifted (assoc-in (s/parked-installer) [:installs 'host.mod :vm]
                     (s/with-op-id (s/parked-writer) :put (op-id 4)))
           (s/header 6 origin #{"s0"}))

   "parked" (lifted (s/parked-explicit) (s/header 1))

   "halted-root" (lifted (s/halted-machine) (s/header 0 origin #{}))})


;; =============================================================================
;; Finding places by predicate
;; =============================================================================

(defn- pending-path
  "The path of the first frame's pending of `body` whose reason is
   `reason`; throws when `body` has none, so a mutation never silently
   misses."
  [body reason]
  (or (some (fn [[i f]]
              (when (= reason (get-in f [:yin.k/pending :yin.k/reason]))
                [:yin.k/frames i :yin.k/pending]))
            (map-indexed vector (:yin.k/frames body)))
      (throw (ex-info "No pending of that reason" {:reason reason}))))


(defn- put-path
  "The path of the first `:put` pending of the base, in the root, or
   with `in`, in the body at `in`."
  ([base] (put-path base []))
  ([base in]
   (into (vec in) (pending-path (get-in base in) :put))))


(defn- id-path
  ([base] (id-path base []))
  ([base in] (conj (put-path base in) :yin.k/op-id)))


(defn- set-in
  [p v]
  #(assoc-in % p v))


(defn- registers-of
  "The registers of `body`'s first frame whose pending reason is `reason`."
  [body reason]
  (get-in body (conj (pop (pending-path body reason)) :yin.k/registers)))


(defn- stream-marker
  "The marker of the base's first cell's stream."
  [body]
  (get-in body [:yin.k/cells :yin.k/c-0 :yin.k/stream]))


;; =============================================================================
;; Mutations: the fixture is (f base)
;; =============================================================================
;;
;; :expected is a function of the base to [path kind] of the refusal;
;; :place a function of the base to the path the mutation changes, when
;; that is not the refusal's path.  The accepted variants and the
;; byte-level fixtures name neither.

(defn- m
  ([n base f] {:name n :base base :f f})
  ([n base f expected] {:name n :base base :f f :expected expected})
  ([n base f expected place]
   {:name n :base base :f f :expected expected :place place}))


(def ^:private mutations
  [;; accepted
   (m "variant-equal" "successor"
      (fn [b]
        (assoc b :yin.k/id-counter 9
               :yin.k/store {:k {:yin.k/tag :yin.k/literal
                                 :yin.k/entries [:a 2]}})))
   (m "variant-different-intent" "successor"
      (fn [b] (assoc-in b (conj (put-path b) :yin.k/value) "w")))
   (m "variant-counter" "successor" (set-in [:yin.k/next-op-seq] 4))
   (m "counter-at-bound" "successor"
      (fn [b]
        (-> b (assoc :yin.k/next-op-seq max-exact)
            (assoc-in (id-path b) (op-id (dec max-exact))))))
   ;; bytes and gate; hash-mismatch and non-canonical change the bytes
   (m "hash-mismatch" "successor" identity)
   (m "non-canonical" "successor" identity)
   (m "version-float" "successor" (set-in [:yin.k/version] (cbor/float64 1)))
   (m "version-2" "successor" (set-in [:yin.k/version] 2))
   (m "version-absent" "successor" #(dissoc % :yin.k/version))
   (m "version-0" "successor" (set-in [:yin.k/version] 0))
   (m "no-tag" "successor" #(dissoc % :yin.k/handoff) (fn [_] [[] :body])
      (fn [_] [:yin.k/handoff]))
   (m "bad-kind" "successor" (set-in [:yin.k/kind] :running)
      (fn [_] [[:yin.k/kind] :running]))
   (m "mixed-child" "installs" (set-in (conj child-path :yin.k/version) 0)
      (fn [_] [(conj child-path :yin.k/version) :mixed-version]))
   ;; root header
   (m "missing-policy" "successor" #(dissoc % :yin.k/policy)
      (fn [_] [[:yin.k/policy] :missing-header]))
   (m "missing-occurrence" "successor" #(dissoc % :yin.k/occurrence)
      (fn [_] [[:yin.k/occurrence] :missing-header]))
   (m "missing-arbitration" "successor" #(dissoc % :yin.k/arbitration)
      (fn [_] [[:yin.k/arbitration] :missing-header]))
   (m "missing-next-op-seq" "successor" #(dissoc % :yin.k/next-op-seq)
      (fn [_] [[:yin.k/next-op-seq] :missing-header]))
   (m "fork-policy" "successor" (set-in [:yin.k/policy] :yin.k/fork)
      (fn [_] [[:yin.k/policy] nil]))
   (m "nil-occurrence" "successor" (set-in [:yin.k/occurrence] nil)
      (fn [_] [[:yin.k/occurrence] :nil-occurrence]))
   (m "occurrence-not-uuid" "successor" (set-in [:yin.k/occurrence] "O")
      (fn [_] [[:yin.k/occurrence] :malformed-occurrence]))
   (m "origin-occurrence-not-uuid" "successor"
      (set-in [:yin.k/origin :yin.k/occurrence] "O")
      (fn [_] [[:yin.k/origin] :malformed-origin])
      (fn [_] [:yin.k/origin :yin.k/occurrence]))
   (m "malformed-arbitration" "successor"
      #(update % :yin.k/arbitration dissoc :dao.stream/descriptor)
      (fn [_] [[:yin.k/arbitration] :malformed-arbitration]))
   (m "origin-is-self" "successor"
      (set-in [:yin.k/origin :yin.k/occurrence] occurrence)
      (fn [_] [[:yin.k/origin :yin.k/occurrence] :origin-is-self]))
   (m "malformed-origin" "successor"
      #(update % :yin.k/origin dissoc :dao.lease/lease)
      (fn [_] [[:yin.k/origin] :malformed-origin]))
   (m "origin-nil-emitter" "successor"
      (set-in [:yin.k/origin :yin.k/emitter] nil)
      (fn [_] [[:yin.k/origin] :malformed-origin])
      (fn [_] [:yin.k/origin :yin.k/emitter]))
   (m "counter-float" "successor"
      (set-in [:yin.k/next-op-seq] (cbor/float64 3))
      (fn [_] [[:yin.k/next-op-seq] :inexact]))
   (m "counter-over-bound" "successor"
      (set-in [:yin.k/next-op-seq] (inc max-exact))
      (fn [_] [[:yin.k/next-op-seq] :inexact]))
   (m "counter-negative" "successor" (set-in [:yin.k/next-op-seq] -1)
      (fn [_] [[:yin.k/next-op-seq] :inexact]))
   (m "first-export-counter" "first-park" (set-in [:yin.k/next-op-seq] 1)
      (fn [_] [[:yin.k/next-op-seq] :first-export-counter]))
   (m "halted-root-header" "halted-root"
      (set-in [:yin.k/occurrence] occurrence)
      (fn [_] [[:yin.k/occurrence] :halted-header]))
   (m "halted-root-without-origin" "halted-root" #(dissoc % :yin.k/origin)
      (fn [_] [[:yin.k/origin] :missing-header]))
   ;; child role and install completeness
   (m "child-header" "installs"
      (set-in (conj child-path :yin.k/occurrence) occurrence)
      (fn [_] [(conj child-path :yin.k/occurrence) :child-header]))
   ;; the child made a halted one, still carrying an origin
   (m "halted-child-origin" "installs"
      #(update-in % child-path
                  (fn [c]
                    (-> c
                        (dissoc :yin.k/frames)
                        (assoc :yin.k/kind :halted :yin.k/result 42
                               :yin.k/origin origin))))
      (fn [_] [(conj child-path :yin.k/origin) :child-header]))
   (m "install-without-entry" "installs"
      #(update % :yin.k/installs dissoc 'host.mod)
      (fn [b] [(pending-path b :install) :incomplete-install])
      (fn [_] [:yin.k/installs]))
   ;; operation ids
   (m "op-id-on-next" "successor"
      (fn [b]
        (assoc-in b (put-path b)
                  {:yin.k/reason :next :yin.k/cell :yin.k/c-0
                   :yin.k/op-id (op-id 1)}))
      (fn [b] [(id-path b) :op-id-on-variant])
      (fn [b] (put-path b)))
   (m "op-id-at-counter" "successor"
      (fn [b] (assoc-in b (conj (id-path b) :yin.k/seq) 3))
      (fn [b] [(conj (id-path b) :yin.k/seq) :op-seq-range]))
   (m "child-op-id-out-of-range" "installs"
      (fn [b] (assoc-in b (conj (id-path b child-path) :yin.k/seq) 6))
      (fn [b] [(conj (id-path b child-path) :yin.k/seq) :op-seq-range]))
   ;; the child's pending copied into the root: the same id twice
   (m "duplicate-op-id" "installs"
      (fn [b]
        (update b :yin.k/frames conj
                {:yin.k/registers (registers-of b :install)
                 :yin.k/pending (get-in b (put-path b child-path))}))
      (fn [b] [(id-path b child-path) :duplicate-op-id])
      (fn [_] [:yin.k/frames]))
   ;; the parked read itself made a write carrying an id, on a first park
   (m "op-id-without-origin" "first-park"
      (fn [b]
        (assoc-in b (pending-path b :next)
                  {:yin.k/reason :put :yin.k/stream (stream-marker b)
                   :yin.k/value 1 :yin.k/op-id (op-id 0)}))
      (fn [b]
        [(conj (pending-path b :next) :yin.k/op-id)
         :op-id-without-origin])
      (fn [b] (pending-path b :next)))
   (m "op-id-own-occurrence" "successor"
      (fn [b] (assoc-in b (conj (id-path b) :yin.k/occurrence) occurrence))
      (fn [b] [(id-path b) :op-id-own-occurrence])
      (fn [b] (conj (id-path b) :yin.k/occurrence)))
   (m "op-id-malformed" "successor"
      (fn [b] (assoc-in b (conj (id-path b) :yin.k/epoch) 0))
      (fn [b] [(id-path b) :malformed-op-id])
      (fn [b] (conj (id-path b) :yin.k/epoch)))
   (m "op-id-occurrence-not-uuid" "successor"
      (fn [b] (assoc-in b (conj (id-path b) :yin.k/occurrence) "O"))
      (fn [b] [(id-path b) :malformed-op-id])
      (fn [b] (conj (id-path b) :yin.k/occurrence)))
   (m "op-id-seq-float" "successor"
      (fn [b] (assoc-in b (conj (id-path b) :yin.k/seq) (cbor/float64 0)))
      (fn [b] [(conj (id-path b) :yin.k/seq) :inexact]))
   (m "op-id-seq-negative" "successor"
      (fn [b] (assoc-in b (conj (id-path b) :yin.k/seq) -1))
      (fn [b] [(conj (id-path b) :yin.k/seq) :inexact]))
   (m "park-reason" "successor"
      (fn [b] (assoc-in b (put-path b) {:yin.k/reason :park}))
      (fn [b] [(put-path b) nil]))])


(def fixtures
  "Fixture name to its body; for hash-mismatch and non-canonical, the
   body whose bytes they change."
  (into base-bodies
        (map (fn [{:keys [name base f]}] [name (f (get base-bodies base))]))
        mutations))


(def fixture-names
  (into ["first-park" "successor" "installs" "parked" "halted-root"]
        (map :name)
        mutations))


(def anchors
  "The fixtures whose full bytes the file keeps."
  #{"first-park" "successor" "installs"})


(defn base-of
  "The name of the base fixture `n` mutates, or nil for a base."
  [n]
  (:base (first (filter #(= n (:name %)) mutations))))


(defn base-body
  "The body of the accepted base `n`."
  [n]
  (get base-bodies n))


(defn expected
  "`[path kind]` of the refusal fixture `n` must draw, computed from its
   base's own shape; nil when `n` has no expectation of this kind."
  [n]
  (when-some [{:keys [base expected]} (first (filter #(= n (:name %))
                                                     mutations))]
    (when expected (expected (get base-bodies base)))))


(defn place
  "The path fixture `n` changed in its base: its own `:place`, or the
   refusal's path.  nil for a fixture that changes only bytes."
  [n]
  (when-some [{:keys [base place]} (first (filter #(= n (:name %))
                                                  mutations))]
    (if place
      (place (get base-bodies base))
      (first (expected n)))))


;; =============================================================================
;; Bytes and pins
;; =============================================================================

(defn segment-address
  "The BLAKE3 segment address of host bytes."
  [bs]
  (keyword "segment" (str "blake3-" (jing/digest-bytes :blake3 bs))))


(defn patch-non-canonical
  "`bs` with its body version 1 written in the two-byte form 0x1801, a
   well-formed CBOR item that does not re-encode to itself."
  [bs]
  (let [k (fx/bytes->hex (cbor/encode :yin.k/version))]
    (fx/hex->bytes (str/replace-first (fx/bytes->hex bs) (str k "01")
                                      (str k "1801")))))


(defn- built-bytes
  "Fixture `n`'s bytes built from its body on this host."
  [n]
  (let [bs (cbor/encode (get fixtures n))]
    (if (= "non-canonical" n) (patch-non-canonical bs) bs)))


(defn- built-address
  "The address pinned for `n`: its bytes' address, except hash-mismatch,
   which pins first-park's."
  [n]
  (segment-address (built-bytes (if (= "hash-mismatch" n) "first-park" n))))


(defn render
  "The fixture file's text, computed from `fixtures`."
  []
  (str/join "\n"
            (map (fn [n]
                   (let [h (when (contains? anchors n)
                             (fx/bytes->hex (built-bytes n)))]
                     (str n "\n" (subs (str (built-address n)) 1) "\n"
                          (apply str
                                 (map #(str (subs h % (min (count h)
                                                           (+ % 64)))
                                            "\n")
                                      (range 0 (count h) 64))))))
                 fixture-names)))


(defn read-file
  "The fixture file as {name {:address a :hex h}}, `h` nil but for an
   anchor."
  []
  (let [blocks (remove #(every? str/blank? %)
                       (partition-by str/blank?
                                     (str/split-lines (fx/read-path path))))]
    (into {}
          (map (fn [[n a & hex]]
                 [n {:address (keyword "segment"
                                       (subs a (count "segment/")))
                     :hex (when (seq hex) (apply str hex))}]))
          blocks)))


(def ^:private file* (delay (read-file)))


(defn fixture
  "Fixture `n`'s pinned address and its bytes: an anchor's from the
   file, non-canonical's patched from the successor anchor's, every
   other built from its body."
  [n]
  (let [{:keys [address hex]} (get @file* n)
        anchor (fn [m] (fx/hex->bytes (:hex (get @file* m))))]
    {:address address
     :bytes (cond
              (some? hex) (fx/hex->bytes hex)
              (= "non-canonical" n) (patch-non-canonical (anchor "successor"))
              :else (cbor/encode (get fixtures n)))}))
