(ns cljd-agg
  "Dart test runner that aggregates the generated test files.

   `flutter test` loads every generated *_test.dart separately (about 7.5 s
   each). This runner compiles the test namespaces through the cljd tool,
   groups the generated files into a few shard files that import them and call
   each `main`, and runs `flutter test` on the shards only. Shards live under
   build/, never under test/, so a plain `cljd test` never runs them twice.

   Run with babashka:
     bb src/dev/cljd_agg.clj [--slow-only | --slow-regex | --only NS,NS...]
   --slow-only restricts the run to the namespaces that use dao.test-slow/guard.
   A namespace in that set with no generated Dart file is fatal.
   --only compiles and runs only the given test namespaces (bb test:changed);
   one with no generated Dart file is fatal too.
   --slow-regex prints, for bb.edn, an anchored alternation of those
   namespaces with its dots already escaped for embedding in an EDN string
   (shadow-cljs --config-merge); it is not a ready-to-use regex. It exits 1
   when no namespace uses the guard, so a slow lane cannot be vacuous.
   DATOM_SLOW_TESTS is inherited from the environment."
  (:require
    [babashka.fs :as fs]
    [babashka.process :as p]
    [clojure.string :as str]))


(def test-root "test")
(def out-root "test/cljd-out")
(def shard-dir "build/cljd-agg")
(def max-shards 8)


(defn- ns-of
  "The namespace declared by the first ns form of `file`."
  [file]
  (second (re-find #"\(ns\s+\^?(?:\{[^}]*\}\s+)?([^\s\)]+)" (slurp file))))


(defn- source-files
  []
  (->> (file-seq (fs/file test-root))
       (filter #(re-find #"_test\.clj[cd]$" (str %)))
       (remove #(str/includes? (str %) "cljd-out"))
       (map str)
       sort))


(defn- test-namespaces
  "Distinct: a namespace with both a .cljc and a .cljd source (for example
   dao.stream.cbor-test) has one generated Dart file, which must run once."
  []
  (distinct (keep ns-of (source-files))))


(defn- slow-namespaces
  "Namespaces whose source uses dao.test-slow/guard, derived from the tree."
  []
  (->> (source-files)
       (filter #(re-find #"slow/guard" (slurp %)))
       (keep ns-of)
       distinct
       sort))


(defn- dart-file
  "Generated file path for namespace `ns-name`."
  [ns-name]
  (str out-root "/" (str/replace ns-name "." "/") "_test.dart"))


(defn- run!*
  [& args]
  (let [{:keys [exit]} (apply p/shell {:continue true} args)]
    exit))


(defn compile-tests
  "Compile every test namespace through the cljd tool."
  [namespaces]
  (let [exit (apply run!* "clojure" "-M:clojuredart:cljd" "compile"
                    namespaces)]
    (when-not (zero? exit)
      (println "cljd compile failed, exit" exit)
      (System/exit exit))))


(defn shard
  "Greedy balanced partition of `files` into `n` groups by file size.
   Deterministic: ties are broken by path."
  [files n]
  (let [sized (sort-by (juxt (comp - fs/size) identity) files)
        init  (vec (repeat n {:size 0 :files []}))]
    (->> sized
         (reduce (fn [shards f]
                   (let [i (first (first (sort-by
                                           (juxt (comp :size second) first)
                                           (map-indexed vector shards))))]
                     (-> shards
                         (update-in [i :size] + (fs/size f))
                         (update-in [i :files] conj f))))
                 init)
         (map (comp sort :files))
         (remove empty?))))


(defn- shard-source
  "Dart source of an aggregator importing `files` and calling each main."
  [files]
  (let [rel (fn [f]
              (str (fs/relativize (fs/absolutize shard-dir)
                                  (fs/absolutize f))))]
    (str "// Generated by src/dev/cljd_agg.clj; do not edit.\n"
         (apply str
                (map-indexed (fn [i f]
                               (str "import '" (rel f) "' as m" i ";\n"))
                             files))
         "\nvoid main() {\n"
         (apply str
                (map-indexed (fn [i _] (str "  m" i ".main();\n")) files))
         "}\n")))


(defn write-shards!
  [files]
  (fs/delete-tree shard-dir)
  (fs/create-dirs shard-dir)
  (let [n (min max-shards
               (.availableProcessors (Runtime/getRuntime))
               (count files))]
    (vec (map-indexed
           (fn [i group]
             (let [path (format "%s/shard_%d_test.dart" shard-dir i)]
               (spit path (shard-source group))
               path))
           (shard files n)))))


(defn -main
  [& args]
  (when (some #{"--slow-regex"} args)
    (when (empty? (slow-namespaces))
      (println "No namespace uses dao.test-slow/guard.")
      (System/exit 1))
    (println (str "^(" (str/join "|" (map #(str/replace % "." "\\\\.")
                                          (slow-namespaces)))
                  ")$"))
    (System/exit 0))
  (let [slow-only? (some #{"--slow-only"} args)
        only       (when (some #{"--only"} args)
                     (let [v (second (drop-while #(not= "--only" %) args))]
                       (vec (remove str/blank? (str/split (str v) #",")))))
        wanted     (cond only only
                         slow-only? (slow-namespaces)
                         :else (test-namespaces))]
    (when (empty? wanted)
      (println "No test namespaces selected.")
      (System/exit 1))
    (compile-tests (or only (test-namespaces)))
    (let [files (filter fs/exists? (map dart-file wanted))
          missing (remove (comp fs/exists? dart-file) wanted)]
      (when (seq missing)
        (println "No generated Dart test for:" (str/join ", " missing))
        (when (or slow-only? only)
          (System/exit 1)))
      (when (empty? files)
        (println "No generated test files found.")
        (System/exit 1))
      (let [shards (write-shards! files)
            _ (println (format "Running %d test files in %d shards"
                               (count files) (count shards)))
            exit (try (apply run!* "flutter" "test"
                             "--concurrency" (str (count shards))
                             shards)
                      (finally (fs/delete-tree shard-dir)))]
        (System/exit exit)))))


(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
