(ns psset-fixtures
  "Generator for the dao.data.btree psset compatibility fixtures
  (docs/design/dao.data.btree.md §5.2, §6 Phase 1).

  Runs on the JVM against persistent-sorted-set 0.3.0 (the version pinned in
  deps.edn) and writes test/dao/data/psset_fixtures.cljc: static EDN node
  blobs in exactly the shape `publish-index!` persists today
  (Leaf {:keys [...]}, Branch {:level n :keys [...] :addresses [...]},
  content-addressed by jing/segment-key), for the fixture matrix
  branching factors 16/32/512 x {sequential bulk build, churned build}.

  Regenerating these fixtures is a deliberate, reviewed act: a diff in the
  generated file is a format-compatibility break (§5.2). Run with:

      clj -M:dev -m psset-fixtures"
  (:require [clojure.java.io :as io]
            [dao.jing :as jing]
            [me.tonsky.persistent-sorted-set :as psset])
  (:import [me.tonsky.persistent_sorted_set ANode Branch IStorage Leaf
            PersistentSortedSet]))


(def psset-version "0.3.0")

(def element-count 1300)     ; 2+ levels at bf 512, 3 levels at bf 16/32
(def churn-ops 2600)         ; seeded conj/disj interleave, drives underflow

;; Same minstd LCG as btree_test.cljc, so the churn is reproducible
(defn- next-seed
  [seed]
  (rem (* 48271 seed) 2147483647))


(defn- churn
  "Interleaved conj/disj (2/3 conj-weighted) over [0, 2*element-count)."
  [set seed n]
  (let [domain (* 2 element-count)]
    (loop [s set
           sd seed
           i 0]
      (if (== i n)
        s
        (let [s1 (next-seed sd)
              k (rem s1 domain)
              s2 (next-seed s1)]
          (recur (if (< (rem s2 3) 2) (conj s k) (disj s k)) s2 (inc i)))))))


(defn- blob-storage
  "psset IStorage capturing blobs into an atom {address blob}, addressed by
  jing/segment-key over the identical blob shapes kv-storage writes."
  [blobs]
  (reify
    IStorage
    (store
      [_ node]
      (let [v (if (instance? Branch node)
                {:level (.level ^Branch node),
                 :keys (vec (.keys ^Branch node)),
                 :addresses (vec (.addresses ^Branch node))}
                {:keys (vec (.keys ^Leaf node))})
            k (jing/segment-key v)]
        (swap! blobs assoc k v)
        k))

    (restore
      [_ _address]
      (throw (ex-info "fixture generator never restores" {})))))


(defn- fixture
  [bf profile]
  (let [base (psset/from-sequential compare
                                    (range element-count)
                                    {:branching-factor bf})
        s (case profile
            :sequential base
            :churned (churn base 20260720 churn-ops))
        blobs (atom {})
        root (psset/store s (blob-storage blobs))]
    {:root root, :count (count s), :elements (vec s), :blobs @blobs}))


(def ^:private header
  (str
    ";; GENERATED by src/dev/psset_fixtures.clj — DO NOT EDIT BY HAND.\n"
    ";; persistent-sorted-set "
    psset-version
    ", elements "
    element-count
    ", churn-ops "
    churn-ops
    ".\n"
    ";; A diff in this file is a storage-format compatibility break\n"
    ";; (docs/design/dao.data.btree.md §5.2) and should be reviewed as one.\n"))


(defn -main
  [& _args]
  (let [fixtures (into (sorted-map)
                       (for [bf [16 32 512]]
                         [bf
                          (into (sorted-map)
                                (for [p [:sequential :churned]]
                                  [p (fixture bf p)]))]))
        f (io/file "test" "dao" "data" "psset_fixtures.cljc")]
    (with-open [w (io/writer f)]
      (.write w header)
      (.write w "(ns dao.data.psset-fixtures)\n\n(def fixtures\n  ")
      (.write
        w
        (binding [*print-length* nil *print-level* nil] (pr-str fixtures)))
      (.write w ")\n"))
    (println "wrote" (str f))
    (doseq [[bf m] fixtures
            [p {:keys [count blobs]}] m]
      (println (format "  bf=%-3d %-11s count=%d segments=%d"
                       bf
                       (name p)
                       count
                       (clojure.core/count blobs))))))
