(ns psset-fixtures
  "Generator for the dao.data.btree psset compatibility fixtures
  (docs/design/dao.data.btree.md section 5.2, section 6 Phase 1).

  Runs on the JVM against persistent-sorted-set 0.3.0 (the version pinned in
  deps.edn) and writes test/dao/data/psset_fixtures.cljc: static EDN node
  blobs in exactly the shape `publish-index!` persists today
  (Leaf {:keys [...]}, Branch {:level n :keys [...] :addresses [...]},
  content-addressed by jing/segment-key), for the fixture matrix
  branching factors 16/32/512 x {sequential bulk build, churned build}.

  Regenerating these fixtures is a deliberate, reviewed act: a diff in the
  generated file is a format-compatibility break (section 5.2). Run with:

      clj -M:dev -m psset-fixtures"
  (:require [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [clojure.string :as str]
            [clojure.walk :as walk]
            [dao.jing :as jing]
            [me.tonsky.persistent-sorted-set :as psset])
  (:import [me.tonsky.persistent_sorted_set Branch IStorage Leaf]))


(def psset-version "0.3.0")

(def element-count 1300)     ; 2+ levels at bf 512, 3 levels at bf 16/32
(def churn-ops 2600)         ; seeded conj/disj interleave, drives underflow

;; Same minstd LCG as btree_test.cljc, so the churn is reproducible
(defn- next-seed
  [seed]
  (rem (* 48271 seed) 2147483647))


(defn- churn
  "Interleaved conj/disj (2/3 conj-weighted) over [0, 2*element-count)."
  [set seed n]
  (let [domain (* 2 element-count)]
    (loop [s set
           sd seed
           i 0]
      (if (== i n)
        s
        (let [s1 (next-seed sd)
              k (rem s1 domain)
              s2 (next-seed s1)]
          (recur (if (< (rem s2 3) 2) (conj s k) (disj s k)) s2 (inc i)))))))


(defn- blob-storage
  "psset IStorage capturing blobs into an atom {address blob}, addressed by
  jing/segment-key over the identical blob shapes kv-storage writes."
  [blobs]
  (reify
    IStorage
    (store
      [_ node]
      (let [v (if (instance? Branch node)
                {:level (.level ^Branch node),
                 :keys (vec (.keys ^Branch node)),
                 :addresses (vec (.addresses ^Branch node))}
                {:keys (vec (.keys ^Leaf node))})
            k (jing/segment-key v)]
        (swap! blobs assoc k v)
        k))

    (restore
      [_ _address]
      (throw (ex-info "fixture generator never restores" {})))))


(defn- fixture
  [bf profile]
  (let [base (psset/from-sequential compare
                                    (range element-count)
                                    {:branching-factor bf})
        s (case profile
            :sequential base
            :churned (churn base 20260720 churn-ops))
        blobs (atom {})
        root (psset/store s (blob-storage blobs))]
    {:root root, :count (count s), :elements (vec s), :blobs @blobs}))


(def ^:private algorithm-id
  "Every fixture address is minted under jing's default algorithm; the
   generated file records the id once and stores bare digests."
  (:address-id (get jing/registry jing/default-hash-algorithm)))


(def ^:private header
  (str
    ";; GENERATED by src/dev/psset_fixtures.clj -- DO NOT EDIT BY HAND.\n"
    ";; persistent-sorted-set "
    psset-version
    ", elements "
    element-count
    ", churn-ops "
    churn-ops
    ".\n"
    ";; A diff in this file is a storage-format compatibility break\n"
    ";; (docs/design/dao.data.btree.md section 5.2) and should be reviewed\n"
    ";; as one. Addresses are written as bare 64-hex digest strings so\n"
    ";; every line fits 80 columns; address-keywords restores the\n"
    ";; :segment/<algorithm>-<hex> keywords at load.\n"))


(def ^:private preamble-lines
  ["(ns dao.data.psset-fixtures"
   "  (:require [clojure.walk :as walk]))"
   ""
   ""
   "(def ^:private digest-text"
   "  #\"[0-9a-f]{64}\")"
   ""
   ""
   "(def ^:private algorithm-id"
   "  \"The one address algorithm every fixture segment was minted under.\""
   "  \"ALGORITHM-ID\")"
   ""
   ""
   "(defn- address-keywords"
   "  \"The fixture tree with every digest string restored to its"
   "   :segment keyword.\""
   "  [x]"
   "  (walk/postwalk (fn [v]"
   "                   (if (and (string? v) (re-matches digest-text v))"
   "                     (keyword \"segment\" (str algorithm-id \"-\" v))"
   "                     v))"
   "                 x))"
   ""])


(defn- preamble
  []
  (str/replace (str/join "\n" preamble-lines) "ALGORITHM-ID" algorithm-id))


(defn- address-strings
  "The fixture tree with every :segment keyword replaced by its bare
   digest; a keyword under any other algorithm is a generator defect."
  [x]
  (walk/postwalk (fn [v]
                   (if (and (keyword? v) (= "segment" (namespace v)))
                     (let [n (name v)
                           prefix (str algorithm-id "-")]
                       (when-not (str/starts-with? n prefix)
                         (throw (ex-info "fixture address: other algorithm"
                                         {:address v})))
                       (subs n (count prefix)))
                     v))
                 x))


(defn- pack-vector
  "Print a vector with fill-style breaks, so scalars pack per line."
  [v]
  ;; print-length-loop binds xs itself; clj-kondo cannot see that
  #_{:clj-kondo/ignore [:unresolved-symbol]}
  (pp/pprint-logical-block
    :prefix "[" :suffix "]"
    (pp/print-length-loop [xs (seq v)]
                          (when xs
                            (pp/write-out (first xs))
                            (when (next xs)
                              (.write ^java.io.Writer *out* " ")
                              (pp/pprint-newline :fill))
                            (recur (next xs))))))


(defn- pretty
  "One fixture pretty-printed within 70 columns, indented 4 spaces so it
   sits inside (def ... (address-keywords ...)); the deepest closing
   brackets after a digest string then end exactly at column 80."
  [x]
  (let [text (binding [pp/*print-right-margin* 70
                       *print-length* nil
                       *print-level* nil]
               (with-out-str
                 (pp/with-pprint-dispatch
                   (fn [o]
                     (if (vector? o) (pack-vector o) (pp/simple-dispatch o)))
                   (pp/pprint x))))]
    (str/join "\n" (map #(if (str/blank? %) % (str "    " %))
                        (str/split-lines text)))))


(defn- fixture-name
  [bf profile]
  (str "bf-" bf "-" (name profile)))


(defn -main
  [& _args]
  (let [fixtures (into (sorted-map)
                       (for [bf [16 32 512]]
                         [bf
                          (into (sorted-map)
                                (for [p [:sequential :churned]]
                                  [p (fixture bf p)]))]))
        f (io/file "test" "dao" "data" "psset_fixtures.cljc")]
    (with-open [w (io/writer f)]
      (.write w header)
      (.write w (preamble))
      (doseq [[bf m] fixtures
              [p fx] m]
        (.write w (str "\n\n(def ^:private " (fixture-name bf p) "\n"
                       "  (address-keywords\n"
                       (pretty (address-strings fx))
                       "))\n")))
      (.write w "\n\n(def fixtures\n")
      (.write w (str/join "\n"
                          (for [[bf m] fixtures]
                            (str "  " (if (= bf 16) "{" " ") bf
                                 " {:churned " (fixture-name bf :churned)
                                 ",\n"
                                 (apply str (repeat (+ 5 (count (str bf)))
                                                    " "))
                                 ":sequential "
                                 (fixture-name bf :sequential) "}"))))
      (.write w "})\n"))
    (println "wrote" (str f))
    (doseq [[bf m] fixtures
            [p {:keys [count blobs]}] m]
      (println (format "  bf=%-3d %-11s count=%d segments=%d"
                       bf
                       (name p)
                       count
                       (clojure.core/count blobs))))))
